// This is an autogenerated file. Do not edit manually. Use gen-ast package.
// Use gen-ast package to generate this file.

use crate::error::*;
use crate::token::*;
use crate::object::*;

pub enum Expr {
    Binary(BinaryExpr),
    Grouping(GroupingExpr),
    Literal(LiteralExpr),
    Unary(UnaryExpr),
}

impl Expr {
    pub fn accept<T>(&self, visitor: &dyn ExprVisitor<T>) -> Result<T, LoxErr> {
        match self {
            Expr::Binary(exp) => exp.accept(visitor),
            Expr::Grouping(exp) => exp.accept(visitor),
            Expr::Literal(exp) => exp.accept(visitor),
            Expr::Unary(exp) => exp.accept(visitor),
        }
    }

}

pub struct BinaryExpr {
    pub left: Box<Expr>,
    pub operator: Token,
    pub right: Box<Expr>,
}

pub struct GroupingExpr {
    pub expression: Box<Expr>,
}

pub struct LiteralExpr {
    pub value: Option<Object>,
}

pub struct UnaryExpr {
    pub operator: Token,
    pub right: Box<Expr>,
}

pub trait ExprVisitor<T> {
    fn visit_binary_expr(&self, expr: &BinaryExpr) -> Result<T, LoxErr>;
    fn visit_grouping_expr(&self, expr: &GroupingExpr) -> Result<T, LoxErr>;
    fn visit_literal_expr(&self, expr: &LiteralExpr) -> Result<T, LoxErr>;
    fn visit_unary_expr(&self, expr: &UnaryExpr) -> Result<T, LoxErr>;
}

impl BinaryExpr {
    pub fn accept<T>(&self, visitor: &dyn ExprVisitor<T>) -> Result<T, LoxErr> {
        visitor.visit_binary_expr(self)
    }
}

impl GroupingExpr {
    pub fn accept<T>(&self, visitor: &dyn ExprVisitor<T>) -> Result<T, LoxErr> {
        visitor.visit_grouping_expr(self)
    }
}

impl LiteralExpr {
    pub fn accept<T>(&self, visitor: &dyn ExprVisitor<T>) -> Result<T, LoxErr> {
        visitor.visit_literal_expr(self)
    }
}

impl UnaryExpr {
    pub fn accept<T>(&self, visitor: &dyn ExprVisitor<T>) -> Result<T, LoxErr> {
        visitor.visit_unary_expr(self)
    }
}

